### ISSUE TITLE
Error when updating Deforum

### ISSUE THREAD

**Issue by Humanoidme** [deforum-art/deforum-stable-diffusion#155]
I am getting the following during reload of A1111

Traceback (most recent call last):
  File "C:\Users\jpdel\stable-diffusion-webui\modules\ui_extensions.py", line 66, in check_updates
    ext.check_updates()
  File "C:\Users\jpdel\stable-diffusion-webui\modules\extensions.py", line 63, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "C:\Users\jpdel\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "C:\Users\jpdel\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 763, in _get_fetch_info_from_stderr
    with open(fetch_head.abspath, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jpdel\\stable-diffusion-webui\\extensions\\deforum\\.git\\FETCH_HEAD'

Can somebody help with a fix? 

Thank you

**Comment by kabachuha** [comment]
Hello! Please, open the issue here instead

https://github.com/deforum-art/deforum-for-automatic1111-webui
