### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by Vendaciousness** [deforum-art/deforum-stable-diffusion#173]
(Using Automatic1111/stable-diffusion-webui)
Saw a similar bug, but there was no traceback, so I'll put up mine.  This happened on frame 715/900. Every long render I've done (over 240 frames) has ended this way in the last few days.

```
Deforum progress: 60092it [11:48:29,  1.41it/s]
Error completing request
Arguments: ('task(48ymrksf2cxqv12)', None, False, '', '3D', 900, 'wrap', '0:(0)', '0: ((0.005 * cos((120 / 60 * 3.141 * (t + 0) / 30))**1 + 1.010))', '0:(0.005)', '0:(0)', '0: ((0.05 * cos((120 / 60 * 3.141 * (t + 0) / 30))**1 + 1.10))', '0:(0)', '0:(0)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.75)', '0: (1.0)', '0: (20)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (95)', '0: (1)', '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', False, '0: ("Euler a")', '0: ("{video_mask}")', False, '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.ckpt")', False, '0: (2)', False, '0: (1.05)', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', 'HSV', '', 1.0, False, 1, 'DIS Fine', True, 10, 'perlin', 8, 8, 4, 0.5, True, 0.2, 'border', 'bicubic', False, 'C:\\Users\\illi\\Pictures\\Input\\blank.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', False, '20230129210106', '{\n    "0": "an equirectangular image of an epic elegant masterpiece mysterious sci-fi matte painting of a crystal cavern full of precious glowing faceted gems lit from within, digital art, dynamic lighting, vibrant colors by  cyril rolando and natalie shau insanely detailed and intricate  --neg animation_prompts_negative\\": \\"humans, character, 1man, 1girl, 1woman, 1child, pets, 1cat, Blurry, ((overexposed)), bad anatomy, deformed, blurred, motion blur, ugly, distorted, deformed, deformation, distortion, artifacts, low quality"\n}', '', '', 1024, 512, True, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Deforum_20230403140440', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0.11, None, False, False, False, False, 'https://deforum.github.io/a1/M1.jpg', 1.0, 1.0, 4, 1, False, 4, 'reroll', 10.0, False, 30, False, False, 'FFMPEG mp4', 'C:\\Users\\Illi\\stable-diffusion-webui\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', '17', 'slow', 'None', 'https://deforum.github.io/a1/A1.mp3', False, 'realesr-animevideov3', 'x2', False, False, 'x0_pred', 'C:/SD/20230124234916_%09d.png', 'testvidmanualsettings.mp4', False, 'None', 2, False, 2, False, None, True, False, 'None', True, 'None', False, 'DIS Fine', False, 'None', False, 'None', False, False, '0:(0.5)', '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', None, None, True, '', '', True, False, False, False, False, 'canny', 'control_sd15_canny [fef5e48e]', 1, 0, 1, 512, 100, 200, 'Scale to Fit (Inner Fit)') {}
Traceback (most recent call last):
  File "C:\Users\Illi\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Illi\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 86, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)
  File "C:\Users\Illi\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 492, in render_animation
    disposable_image = generate(args, keys, anim_args, loop_args, controlnet_args, root, frame_idx, sampler_name=scheduled_sampler_name)
  File "C:\Users\Illi\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\generate.py", line 60, in generate
    image, caught_vae_exception = generate_with_nans_check(args, keys, anim_args, loop_args, controlnet_args, root, frame, return_sample, sampler_name)
  File "C:\Users\Illi\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\generate.py", line 94, in generate_with_nans_check
    raise e
  File "C:\Users\Illi\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\generate.py", line 88, in generate_with_nans_check
    image = generate_inner(args, keys, anim_args, loop_args, controlnet_args, root, frame, return_sample, sampler_name)
  File "C:\Users\Illi\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\generate.py", line 263, in generate_inner
    processed = processing.process_images(p)
  File "C:\Users\Illi\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "C:\Users\Illi\stable-diffusion-webui\modules\processing.py", line 655, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\Illi\stable-diffusion-webui\modules\processing.py", line 655, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\Illi\stable-diffusion-webui\modules\processing.py", line 440, in decode_first_stage
    x = model.decode_first_stage(x)
  File "C:\Users\Illi\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\Illi\stable-diffusion-webui\modules\sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\modules\sd_hijack_unet.py", line 76, in <lambda>
    first_stage_sub = lambda orig_func, self, x, **kwargs: orig_func(self, x.to(devices.dtype_vae), **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "C:\Users\Illi\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "C:\Users\Illi\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "C:\Users\Illi\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  [Previous line repeated 958 more times]
  File "C:\Users\Illi\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 630, in forward
    h = self.mid.block_1(h, temb)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 133, in forward
    h = self.conv1(h)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Illi\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 319, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 458, in _conv_forward
    _pair(0), self.dilation, self.groups)
  File "C:\Users\Illi\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\utils.py", line 9, in parse
    if isinstance(x, collections.abc.Iterable):
  File "C:\Users\Illi\AppData\Local\Programs\Python\Python310\lib\abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```
I think **Deforum** is the most valuable extension ever made for Stable Diffusion **_by far_** and I appreciate you guys **SO MUCH!  Thank you!!!**

**Comment by aleatorydialogue** [comment]
I have been having the same sort of issue, did you figure this out?

**Comment by Vendaciousness** [comment]
Unfortunately, not yet.  It still happened a few times since I wrote up the
bug, but not in the last few days.  Instead, I'll come back in the morning
and find Chrome has crashed, but SD keeps running the job, so it's okay, I
guess...lol

I may not be getting it anymore because I reinstalled my SD and removed all
the SD plugins I wasn't actively using, as I've had Deforum crash due to
other extensions numerous times. Ones I recall crashing it are the
Additional Networks, Multidiffusion & Tiled VAE.

These webui-user.bat args also may help with Deforum issues "--xformers
--force-enable-xformers" and "--reinstall-xformers" will reinstall xformers
(just remove it after running it once) may have helped me.  I also use
"--medvram --opt-split-attention-v1" and I don't get Out of Memory errors
anymore.

Sorry I couldn't help. Definitely join the Deforum Discord if you haven't
already. There's a ton of info that's nowhere else on the net. You can use
the search function in the top right corner while in the server to search
for your problems.
I'm Vendacious#6006 on there, so add me if you like. I'm planning on using
Deforum a lot, now that I'm getting more consistent results.
-V

**Comment by Kashyap1237** [comment]
**Facing a similar issue today! @Vendaciousness i feel your pain.
Deforum is my favorite extension on Automatic 1111 and i respect the work of @huemin-art and the team
But now facing this issue of "maximum recursion depth exceeded" is so sad - I'm using A1111, and in Deforum, when i'm generating images, it stops at 1905/2000 frame. - Though i can resume the animation from there (1905 frame), but this wasn't happening earlier. - i'm sharing the log from before the point it stopped generating images.-  the most crucial thing is that even at Steps = 1 , the same thing happens.** 
.
.
.
Animation frame: 1904/2001
Creating in-between cadence frame: 1902; tween:0.50;
Creating in-between cadence frame: 1903; tween:1.00;
Seed: 1905
Prompt: ((high quality)), ((centered)) , ((detail))
  abstract artwork, lines and shapes
Neg Prompt: ((low-res)), ((((text)))), error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature, children, child, girl, boy, ((human)), ((people)), (((man))), (((woman))), ((girl)), (((high contrast))), ((highly saturated colors)), cropped, worst quality, ((low quality)),  ((low res)),  (((text, watermark))), (((logo))), (((words))), (((city))), (((houses))), ((fairy)), (((Characters))), (((cars))), ((vehicles)), (girl), (((face))), (((person))), ((anime)), ((anime boy)), (((anime girl))), (((doll))
Applying xformers cross attention optimization.
╭─────┬───┬───────┬─────────────────────────────────┬────┬────┬────┬────┬────┬────╮
│Steps│CFG│Denoise│           Checkpoint            │Tr X│Tr Y│Tr Z│Ro X│Ro Y│Ro Z│
├─────┼───┼───────┼─────────────────────────────────┼────┼────┼────┼────┼────┼────┤
│  0  │7.0│  0.2  │dreamshaper_5BakedVae.safetensors│0.5 │0.5 │ 0  │ 0  │ 0  │ 0  │
╰─────┴───┴───────┴─────────────────────────────────┴────┴────┴────┴────┴────┴────╯
0it [00:00, ?it/s]
Animation frame: 1906/2001
Creating in-between cadence frame: 1904; tween:0.50;
Creating in-between cadence frame: 1905; tween:1.00;
Seed: 1907
Prompt: ((high quality)), ((centered)) , ((detail))
  abstract artwork, lines and shapes
Neg Prompt: ((low-res)), ((((text)))), error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature, children, child, girl, boy, ((human)), ((people)), (((man))), (((woman))), ((girl)), (((high contrast))), ((highly saturated colors)), cropped, worst quality, ((low quality)),  ((low res)),  (((text, watermark))), (((logo))), (((words))), (((city))), (((houses))), ((fairy)), (((Characters))), (((cars))), ((vehicles)), (girl), (((face))), (((person))), ((anime)), ((anime boy)), (((anime girl))), (((doll))
Applying xformers cross attention optimization.
╭─────┬───┬───────┬─────────────────────────────────┬────┬────┬────┬────┬────┬────╮
│Steps│CFG│Denoise│           Checkpoint            │Tr X│Tr Y│Tr Z│Ro X│Ro Y│Ro Z│
├─────┼───┼───────┼─────────────────────────────────┼────┼────┼────┼────┼────┼────┤
│  0  │7.0│  0.3  │dreamshaper_5BakedVae.safetensors│0.5 │0.5 │ 4  │ 0  │ 0  │ 0  │
╰─────┴───┴───────┴─────────────────────────────────┴────┴────┴────┴────┴────┴────╯
0it [00:00, ?it/s]

*START OF TRACEBACK*
Traceback (most recent call last):
  File "C:\NEW SD\stable-diffusion-webui\extensions\deforum\scripts\deforum.py", line 109, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)  File "C:\NEW SD\stable-diffusion-webui/extensions/deforum/scripts\deforum_helpers\render.py", line 550, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, root, frame_idx, sampler_name=scheduled_sampler_name)
  File "C:\NEW SD\stable-diffusion-webui/extensions/deforum/scripts\deforum_helpers\generate.py", line 64, in generate
    image, caught_vae_exception = generate_with_nans_check(args, keys, anim_args, loop_args, controlnet_args, root, frame, return_sample, sampler_name)
  File "C:\NEW SD\stable-diffusion-webui/extensions/deforum/scripts\deforum_helpers\generate.py", line 98, in generate_with_nans_check
    raise e
  File "C:\NEW SD\stable-diffusion-webui/extensions/deforum/scripts\deforum_helpers\generate.py", line 92, in generate_with_nans_check
    image = generate_inner(args, keys, anim_args, loop_args, controlnet_args, root, frame, return_sample, sampler_name)
  File "C:\NEW SD\stable-diffusion-webui/extensions/deforum/scripts\deforum_helpers\generate.py", line 267, in generate_inner
    processed = processing.process_images(p)
  File "C:\NEW SD\stable-diffusion-webui\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\NEW SD\stable-diffusion-webui\modules\processing.py", line 671, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\NEW SD\stable-diffusion-webui\modules\processing.py", line 671, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\NEW SD\stable-diffusion-webui\modules\processing.py", line 444, in decode_first_stage
    x = model.decode_first_stage(x)
  File "C:\NEW SD\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\NEW SD\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\NEW SD\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "C:\NEW SD\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "C:\NEW SD\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "C:\NEW SD\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  [Previous line repeated 959 more times]
  File "C:\NEW SD\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\NEW SD\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 631, in forward
    h = self.mid.attn_1(h)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\NEW SD\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 258, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 294, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 310, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 98, in _dispatch_fw    return _run_priority_list(
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 63, in _run_priority_list
    not_supported = op.not_supported_reasons(inp)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 213, in not_supported_reasons
    matmul_alignment_mn = _minimum_gemm_alignment(d)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 42, in _minimum_gemm_alignment
    cap = torch.cuda.get_device_capability(inp.device)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    if is_initialized() or hasattr(_tls, 'is_initializing'):
  File "C:\NEW SD\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py", line 178, in is_initialized
    return _initialized and not _is_in_bad_fork()
RecursionError: maximum recursion depth exceeded while calling a Python object
*END OF TRACEBACK*

User friendly error message:
Error: maximum recursion depth exceeded while calling a Python object. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \.

**Comment by Kashyap1237** [comment]
I also tried increasing the maximum recursion depth on CMD, by using " sys.setrecursionlimit(1500) " . but it keeps resetting back to 1000.

**Comment by aleatorydialogue** [comment]
I got an egpu with more vram and no longer used medvram parameter and
haven't had this error ever since. I had been having it almost every run.
So clearly something to do with trying to optimize for low vram.

**Comment by Vendaciousness** [comment]
I'm sure sure what I've changed, but I no longer get this, usually. I'm guessing it was either upgrading my torch to 2.01, or adding '--opt-sdp-attention' to my commandline args.

You can upgrade your torch with this command:
```pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118```

Then you can add this to your webui-user.bat:
```set TORCH_COMMAND=pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118```
