### ISSUE TITLE
Input type (MPSFloatType) and weight type (MPSHalfType) should be the same.

### ISSUE THREAD

**Issue by ReNNNNNa** [deforum-art/deforum-stable-diffusion#188]
I use a MacBookPro 16" 2019.

this error show up only in 3D mode with MiDaS enabled 
commit ba9c854

here is the error:

>Deforum extension for auto1111 webui, v2.3b
Git commit: ba9c8540 (Fri Apr 28 11:51:43 2023)
Saving animation frames to:
/Users/administrator/stable-diffusion-webui/outputs/img2img-images/Deforum_20230428141531
Loading MiDaS model...
Loading AdaBins model...
Using cache found in /Users/administrator/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Animation frame: 0/120  
Seed: 811450341
Prompt: tiny cute swamp bunny, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Not using an init image (doing pure txt2img)
╭─────┬───┬───────┬────┬────┬────┬────┬────┬────╮
│Steps│CFG│Denoise│Tr X│Tr Y│Tr Z│Ro X│Ro Y│Ro Z│
├─────┼───┼───────┼────┼────┼────┼────┼────┼────┤
│ 25  │7.0│ None  │ 0  │ 0  │ 7  │ 0  │ 0  │ 0  │
╰─────┴───┴───────┴────┴────┴────┴────┴────┴────╯
100%|███████████████████████████████████████████| 25/25 [01:14<00:00,  2.98s/it]
Animation frame: 3/120  ▌                      | 25/376 [00:58<13:41,  2.34s/it]
Creating in-between cadence frame: 0; tween:0.33;

>*START OF TRACEBACK*
Traceback (most recent call last):
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum.py", line 109, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/render.py", line 303, in render_animation
    depth = depth_model.predict(turbo_next_image, anim_args.midas_weight, root.half_precision)
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/depth.py", line 103, in predict
    midas_depth = self.midas_model.forward(sample)
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/src/midas/dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/src/midas/dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/src/midas/backbones/vit.py", line 13, in forward_vit
    return forward_adapted_unflatten(pretrained, x, "forward_flex")
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/src/midas/backbones/utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")
  File "<string>", line 1, in <module>
  File "/Users/administrator/stable-diffusion-webui/extensions/deforum/scripts/deforum_helpers/src/midas/backbones/vit.py", line 47, in forward_flex
    x = self.patch_embed.proj(x).flatten(2).transpose(1, 2)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/administrator/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 319, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same
*END OF TRACEBACK*

>User friendly error message:
Error: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same. Check your schedules/ init values please. Also make sure you don't have a forward slash in any of your PATHs - use / instead of \.
Deforum progress:   7%|█▌                      | 25/376 [01:00<14:07,  2.41s/it]

this doesn't happen with commit fbe6eab

**Comment by hithereai** [comment]
Wrong repo.
