### ISSUE TITLE
No Tab showing in A1111

### ISSUE THREAD

**Issue by Jaulustus** [deforum-art/deforum-stable-diffusion#219]
Have an error while starting A1111 and than its show me this error:
 Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 298, in on_ui_tabs
    component_list = [components[name] for name in deforum_args.get_component_names()]
  File "C:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 298, in <listcomp>
    component_list = [components[name] for name in deforum_args.get_component_names()]
KeyError: 'cn_1_overwrite_frames'

I have the newest update

**Comment by hithereai** [comment]
Wrong repo
