### ISSUE TITLE
upsample_bilinear2d_channels_last

### ISSUE THREAD

**Issue by kbachnik** [deforum-art/deforum-stable-diffusion#222]
I tried everything. In the end, the error does not go anywhere. I have the version of Python 3.10.6 I'm at a dead end, I can't find any other solution to the problem anywhere else. Please help!

Im trying to use Python 3.11.3 but have an issue 
```
"INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.3.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory."
```

My PC configuration :
Windows 11 Home 64-bit
CPU :  Intel Core i7 @ 3.00GHz  44 °C
Motherboard :  Microsoft Corporation Surface Laptop 4 (U3E1)
Graphics :  LQ150P1JX51 (2496x1664@60Hz) Intel Iris Xe Graphics (Microsoft)

Error: '"upsample_bilinear2d_channels_last" not implemented for 'Half''. Check your schedules/ init values please. Also make sure you don't have a forward slash in any of your PATHs - use / instead of \.

![image](https://github.com/deforum-art/deforum-stable-diffusion/assets/36343167/15c42c47-82d5-4ab3-9caa-09cbf0d642a1)

![image](https://github.com/deforum-art/deforum-stable-diffusion/assets/36343167/93faee7e-3aa5-42bc-9839-7a6cd6e14c93)

Phython on disc C, stable diffusion on Disk D

![image](https://github.com/deforum-art/deforum-stable-diffusion/assets/36343167/071e4673-2a9e-463b-8664-a8d1f08d895c)

**Comment by kbachnik** [comment]
Here the full issue if im trying to use 3.11.3
```
venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
==============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.3.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3106/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\launch.py", line 369, in <module>
    prepare_environment()
  File "D:\AI\stable-diffusion-webui\launch.py", line 313, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements")
  File "D:\AI\stable-diffusion-webui\launch.py", line 143, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\stable-diffusion-webui\launch.py", line 111, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements.
Command: "D:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Collecting blendmodes==2022
  Using cached blendmodes-2022-py3-none-any.whl (10 kB)
Collecting transformers==4.25.1
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Collecting accelerate==0.18.0
  Using cached accelerate-0.18.0-py3-none-any.whl (215 kB)
Requirement already satisfied: basicsr==1.4.2 in d:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 4)) (1.4.2)
Collecting gfpgan==1.3.8
  Using cached gfpgan-1.3.8-py3-none-any.whl (52 kB)
Collecting gradio==3.29.0
  Using cached gradio-3.29.0-py3-none-any.whl (17.3 MB)
Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp311-cp311-win_amd64.whl (14.6 MB)
Collecting Pillow==9.4.0
  Using cached Pillow-9.4.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting realesrgan==0.3.0
  Using cached realesrgan-0.3.0-py3-none-any.whl (26 kB)
Requirement already satisfied: torch in d:\ai\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 10)) (2.0.1+cu118)
Collecting omegaconf==2.2.3
  Using cached omegaconf-2.2.3-py3-none-any.whl (79 kB)
Collecting pytorch_lightning==1.9.4
  Using cached pytorch_lightning-1.9.4-py3-none-any.whl (827 kB)
Collecting scikit-image==0.19.2
  Using cached scikit-image-0.19.2.tar.gz (22.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: still running...
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting fonts
  Using cached fonts-0.0.3-py3-none-any.whl (4.2 kB)
Collecting font-roboto
  Using cached font_roboto-0.0.1-py3-none-any.whl
Collecting timm==0.6.7
  Using cached timm-0.6.7-py3-none-any.whl (509 kB)
Collecting piexif==1.1.3
  Using cached piexif-1.1.3-py2.py3-none-any.whl (20 kB)
Collecting einops==0.4.1
  Using cached einops-0.4.1-py3-none-any.whl (28 kB)
```

**Comment by deforum** [comment]
this is an issue for the auto extension, not the notebook. repost here: https://github.com/deforum-art/sd-webui-deforum/issues but i do not recommend tinkering with versions - use what works and dont waste time with other stuff
