### ISSUE TITLE
No module named ldm

### ISSUE THREAD

**Issue by usamaa-saleem** [deforum-art/deforum-stable-diffusion#227]
```shell
(env) ubuntu@129-213-88-168:~/deforum/deforum-stable-diffusion$ python Deforum_Stable_Diffusion.py 
Traceback (most recent call last):
  File "/home/ubuntu/deforum/deforum-stable-diffusion/Deforum_Stable_Diffusion.py", line 10, in <module>
    from helpers.render import render_animation, render_input_video, render_image_batch, render_interpolation
  File "/home/ubuntu/deforum/deforum-stable-diffusion/helpers/render.py", line 15, in <module>
    from .generate import generate, add_noise
  File "/home/ubuntu/deforum/deforum-stable-diffusion/helpers/generate.py", line 8, in <module>
    from ldm.models.diffusion.plms import PLMSSampler
ModuleNotFoundError: No module named 'ldm'
``` 

How do I set this error?

**Comment by usamaa-saleem** [comment]
@reallybigname any idea?

**Comment by usamaa-saleem** [comment]
Done, found the way.

**Comment by Pipickin** [comment]
@usamaa-saleem Hello!
I have faced with the same issue:
No module named 'ldm.models.diffusion.ddpm'
How did you fix that?

Thanks in advance
