### ISSUE TITLE
Error: 'local variable 'value_is_number' referenced before assignment'.

### ISSUE THREAD

**Issue by mytricker0** [deforum-art/deforum-stable-diffusion#231]
when clicking generate, I get this error :
Deforum extension for auto1111 webui, v2.4b
Git commit: 7012f55b (Wed May 24 15:53:20 2023)

*START OF TRACEBACK*
Traceback (most recent call last):
  File "/home/bro/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/run_deforum.py", line 76, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "/home/bro/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/render.py", line 68, in render_animation
    keys = DeformAnimKeys(anim_args, args.seed) if not use_parseq else ParseqAnimKeys(parseq_args, anim_args, video_args)
  File "/home/bro/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/animation_key_frames.py", line 19, in __init__
    self.rotation_3d_z_series = self.fi.get_inbetweens(self.fi.parse_key_frames(anim_args.rotation_3d_z))
  File "/home/bro/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/animation_key_frames.py", line 99, in get_inbetweens
    if not value_is_number:
UnboundLocalError: local variable 'value_is_number' referenced before assignment
*END OF TRACEBACK*

User friendly error message:
Error: local variable 'value_is_number' referenced before assignment. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \.

this is the init category:
![image](https://github.com/deforum-art/deforum-stable-diffusion/assets/58003204/5ba8eac9-0e1b-4ca4-a043-65d3714878c8)

and the keyframes:
![image](https://github.com/deforum-art/deforum-stable-diffusion/assets/58003204/d8587900-e2a6-4ef2-8647-db9998c49ebc)

**Comment by hithereai** [comment]
Wrong repo
