### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\temp\\gradio\\tmpefx623gt.png'

### ISSUE THREAD

**Issue by GamersGold** [deforum-art/deforum-stable-diffusion#243]
Anyone who know what this mean, I get it on non TensorRT models too. 

:-)

**Comment by GamersGold** [comment]
So it worked after fresh install of Deforum and SD. Then there was a strange download from Deforum and now it does not work. The TensorRT can work with Deforum and I got 40 iterations / s 
But then after this download there is a conflict on the Deforum extension.

**Comment by GamersGold** [comment]
User friendly error message:
Error: bad shape for TensorRT input x: (2, 4, 67, 120). Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \.
2023-05-31 18:02:13,417 - httpx - INFO - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-05-31 18:02:13,427 - httpx - INFO - HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Comment by GamersGold** [comment]
This is made without Tensor RT, but still there is errors?

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\doubt\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\doubt\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\doubt\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\temp\\gradio\\tmp0gf3tkss.png'
2023-05-31 18:32:52,722 - httpx - INFO - HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
