### ISSUE TITLE
Vid2Depth Depth/Midas mode AttributeError

### ISSUE THREAD

**Issue by firehawkx** [deforum-art/deforum-stable-diffusion#272]
In auto1111/deforum/Vid2Depth, I load in my short 7 sec video that I want to create a depth map.

Anime Remove Background works fine, 
however both "mixed" and Depth(Midas/Adabins) "crash" with the following error log :

If anyone has any suggestion it would be appreciated :)

`
```
got a request to *vid2depth* an existing video.

Trying to extract frames from video with input FPS of 30.0. Please wait patiently.

Extracted 179 frames from video in 1.35 seconds!

Vid2depth progress (it's OK if it finishes before 100%):

Loading Depth Model

Loading MiDaS model from dpt_large-midas-2f21e586.pt...

Vid2depth:   0%|                                                                               | 0/179 [00:00<?, ?it/s]

Traceback (most recent call last):

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\gradio_funcs.py", line 132, in upload_vid_to_depth

    process_depth_vid_upload_logic(vid_to_depth_chosen_file, mode, thresholding, threshold_value, threshold_value_max, adapt_block_size, adapt_c, invert, end_blur, midas_weight_vid2depth,

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\vid2depth.py", line 32, in process_depth_vid_upload_logic

    process_video_depth(mode, thresholding, threshold_value, threshold_value_max, adapt_block_size, adapt_c, invert, end_blur, midas_weight_vid2depth, orig_vid_fps=in_vid_fps, real_audio_track=file.name, raw_output_imgs_path=outdir, img_batch_id=None, ffmpeg_location=f_location, ffmpeg_crf=f_crf, ffmpeg_preset=f_preset, f_models_path=f_models_path, keep_depth_imgs=keep_imgs, orig_vid_name=folder_name)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\vid2depth.py", line 74, in process_video_depth
    image = process_frame(model, Image.open(img_path).convert("RGB"), mode, thresholding, threshold_value, threshold_value_max, adapt_block_size, adapt_c, invert, end_blur, midas_weight_vid2depth)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\vid2depth.py", line 102, in process_frame
    depth = process_frame_depth(model, np.array(image), midas_weight_vid2depth) if 'Depth' in mode else process_frame_anime(model, np.array(image))

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\vid2depth.py", line 222, in process_frame_depth
    depth = depth_model.predict(opencv_image, midas_weight, not cmd_opts.no_half)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\depth.py", line 88, in predict
    depth_tensor = self.midas_depth.predict(prev_img_cv2, half_precision)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\depth_midas.py", line 60, in predict
    midas_depth = self.midas_model.forward(sample)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\src\midas\dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\src\midas\dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\src\midas\backbones\vit.py", line 13, in forward_vit
    return forward_adapted_unflatten(pretrained, x, "forward_flex")

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\src\midas\backbones\utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")

  File "<string>", line 1, in <module>

  File "C:\AI\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\src\midas\backbones\vit.py", line 56, in forward_flex
    if self.no_embed_class:

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(

AttributeError: 'VisionTransformer' object has no attribute 'no_embed_class'
```
`

**Comment by deforum** [comment]
for auto issues please use https://github.com/deforum-art/sd-webui-deforum/issues
