### ISSUE TITLE
"Could not find module <...>\libtorchaudio.pyd" after installations from scratch. 

### ISSUE THREAD

**Issue by zakharsk** [deforum-art/deforum-stable-diffusion#296]
Hello. I am trying to run Deforum Stable Diffusion following exactly the instructions in the README.

At the startup stage at the very end the script crashes with an error from the header. As a simple countermeasure, I tried adjusting the Python version of the installation from 3.10 to 3.10.6, but that didn't work.

Do you have any suggestions as to which way to dig? It looks like it's not a regular dependency problem, the script just doesn't see the library that's at the right address.

[System]
```
OS Name	Microsoft Windows 11 Home Single Language
Version	10.0.22621 Build 2262
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 Mhz, 4 Core(s), 8 Logical Processor(s)
Total Physical Memory	15.8 GB
```

[Display 1]
```
Intel(R) UHD Graphics (Disabled from the Device Manager)
```

[Display 2]
```
NVIDIA GeForce GTX 1650 Ti
Driver version:		536.67
Dedicated video memory:	4096 MB GDDR6
```

[ffmpeg]
```
ffmpeg version 2023-07-16-git-c541ecf0dc-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
```

[CUDA]
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

[Anaconda]
```
# packages in environment at %USER_NAME%\anaconda3\envs\dsd:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albumentations            1.3.1                    pypi_0    pypi
annotated-types           0.5.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-lru                 2.0.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
boltons                   23.0.0                   pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2023.05.30           haa95532_0
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
clean-fid                 0.1.35                   pypi_0    pypi
colab-convert             2.0.5                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
devtools                  0.11.0                   pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.17.1                   pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
fonttools                 4.41.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
google-auth               2.22.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.56.2                   pypi_0    pypi
huggingface-hub           0.16.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.1                   pypi_0    pypi
ipykernel                 6.24.0                   pypi_0    pypi
ipython                   8.14.0                   pypi_0    pypi
ipywidgets                8.0.7                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.1                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonmerge                 1.9.2                    pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.18.4                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
jupyter-client            8.3.0                    pypi_0    pypi
jupyter-core              5.3.1                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-http-over-ws      0.0.8                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            2.7.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.3                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.23.0                   pypi_0    pypi
jupyterlab-widgets        3.0.8                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.6.12                   pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
lightning-utilities       0.9.0                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   3.0.1                    pypi_0    pypi
more-itertools            9.1.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
nbclient                  0.8.0                    pypi_0    pypi
nbconvert                 7.7.2                    pypi_0    pypi
nbformat                  5.9.1                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
notebook                  7.0.0                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numexpr                   2.8.4                    pypi_0    pypi
numpngw                   0.1.2                    pypi_0    pypi
numpy                     1.25.1                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open-clip-torch           2.20.0                   pypi_0    pypi
opencv-python             4.8.0.74                 pypi_0    pypi
opencv-python-headless    4.8.0.74                 pypi_0    pypi
openssl                   1.1.1u               h2bbff1b_0
overrides                 7.3.1                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.1.2          py310haa95532_0
platformdirs              3.9.1                    pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  2.0.3                    pypi_0    pypi
pydantic-core             2.3.0                    pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.10.6               hbb2ffb3_1
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytorch-lightning         1.7.7                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.11                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.0                   pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
referencing               0.30.0                   pypi_0    pypi
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resize-right              0.0.2                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.9.2                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.1                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                67.8.0          py310haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack-data                0.6.2                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.1                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.18                pypi_0    pypi
timm                      0.9.2                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tokenizers                0.12.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchaudio                2.1.0.dev20230719+cu121          pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchmetrics              1.0.1                    pypi_0    pypi
torchsde                  0.2.5                    pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tornado                   6.3.2                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
trampoline                0.1.2                    pypi_0    pypi
transformers              4.19.2                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.16                  pypi_0    pypi
validators                0.20.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
werkzeug                  2.3.6                    pypi_0    pypi
wheel                     0.38.4          py310haa95532_0
widgetsnbextension        4.0.8                    pypi_0    pypi
xz                        5.4.2                h8cc25b3_0
yarl                      1.9.2                    pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
```

[Full error stack]
 The script is executed from `Anaconda Shell Prompt` with the `dsd` environment activated
```
(dsd) PS %USER_NAME%\Ai\deforum-stable-diffusion> python Deforum_Stable_Diffusion.py
NVIDIA GeForce GTX 1650 Ti, 4096 MiB, 3842 MiB
..skipping setup
Traceback (most recent call last):
  File "%USER_NAME%\Ai\deforum-stable-diffusion\Deforum_Stable_Diffusion.py", line 82, in <module>
    from helpers.render import render_animation, render_input_video, render_image_batch, render_interpolation
  File "%USER_NAME%\Ai\deforum-stable-diffusion\helpers\render.py", line 15, in <module>
    from .generate import generate, add_noise
  File "%USER_NAME%\Ai\deforum-stable-diffusion\helpers\generate.py", line 9, in <module>
    from pytorch_lightning import seed_everything
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\pytorch_lightning\__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\pytorch_lightning\utilities\types.py", line 28, in <module>
    from torchmetrics import Metric
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\functional\audio\pit.py", line 23, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchmetrics\utilities\imports.py", line 48, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\lightning_utilities\core\imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "%USER_NAME%\anaconda3\envs\dsd\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchaudio\_extension\__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torchaudio\_extension\utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "%USER_NAME%\anaconda3\envs\dsd\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "%USER_NAME%\anaconda3\envs\dsd\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module '%USER_NAME%\anaconda3\envs\dsd\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

[TorchAudio directory listing]
```
PS %USER_NAME%\anaconda3\envs\dsd\Lib\site-packages\torchaudio\lib> dir


    Directory: %USER_NAME%\anaconda3\envs\dsd\Lib\site-packages\torchaudio\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         7/20/2023   2:00 PM        4780032 libctc_prefix_decoder.pyd
-a----         7/20/2023   2:00 PM        2624512 libtorchaudio.pyd
-a----         7/20/2023   2:00 PM        1225216 libtorchaudio_ffmpeg4.pyd
-a----         7/20/2023   2:00 PM        1225216 libtorchaudio_ffmpeg5.pyd
-a----         7/20/2023   2:00 PM        1225216 libtorchaudio_ffmpeg6.pyd
-a----         7/20/2023   2:00 PM         665600 pybind11_prefixctc.pyd
-a----         7/20/2023   2:00 PM         776704 _torchaudio.pyd
-a----         7/20/2023   2:00 PM        1707520 _torchaudio_ffmpeg4.pyd
-a----         7/20/2023   2:00 PM        1707520 _torchaudio_ffmpeg5.pyd
-a----         7/20/2023   2:00 PM        1707520 _torchaudio_ffmpeg6.pyd
```

**Comment by nitinmukesh** [comment]
Did you find the solution?
I am facing the same problem

> (dsd) D:\deforum\deforum-stable-diffusion>python Deforum_Stable_Diffusion.py
> NVIDIA GeForce GTX 1650 with Max-Q Design, 4096 MiB, 3949 MiB
> ..skipping setup
> Traceback (most recent call last):
>   File "D:\deforum\deforum-stable-diffusion\Deforum_Stable_Diffusion.py", line 82, in <module>
>     from helpers.render import render_animation, render_input_video, render_image_batch, render_interpolation
>   File "D:\deforum\deforum-stable-diffusion\helpers\render.py", line 15, in <module>
>     from .generate import generate, add_noise
>   File "D:\deforum\deforum-stable-diffusion\helpers\generate.py", line 9, in <module>
>     from pytorch_lightning import seed_everything
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\pytorch_lightning\__init__.py", line 34, in <module>
>     from pytorch_lightning.callbacks import Callback  # noqa: E402
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
>     from pytorch_lightning.callbacks.callback import Callback
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
>     from pytorch_lightning.utilities.types import STEP_OUTPUT
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\pytorch_lightning\utilities\types.py", line 28, in <module>
>     from torchmetrics import Metric
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
>     from torchmetrics import functional  # noqa: E402
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
>     from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
>     from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\functional\audio\pit.py", line 23, in <module>
>     from torchmetrics.utilities import rank_zero_warn
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\utilities\__init__.py", line 14, in <module>
>     from torchmetrics.utilities.checks import check_forward_full_state_property
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\utilities\checks.py", line 25, in <module>
>     from torchmetrics.metric import Metric
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\metric.py", line 30, in <module>
>     from torchmetrics.utilities.data import (
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\utilities\data.py", line 22, in <module>
>     from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchmetrics\utilities\imports.py", line 50, in <module>
>     _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\lightning_utilities\core\imports.py", line 73, in compare_version
>     pkg = importlib.import_module(package)
>   File "C:\Users\nitin\.conda\envs\dsd\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
>     from . import (  # noqa: F401
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchaudio\_extension\__init__.py", line 45, in <module>
>     _load_lib("libtorchaudio")
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torchaudio\_extension\utils.py", line 64, in _load_lib
>     torch.ops.load_library(path)
>   File "C:\Users\nitin\.conda\envs\dsd\lib\site-packages\torch\_ops.py", line 643, in load_library
>     ctypes.CDLL(path)
>   File "C:\Users\nitin\.conda\envs\dsd\lib\ctypes\__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> FileNotFoundError: Could not find module 'C:\Users\nitin\.conda\envs\dsd\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by zakharsk** [comment]
@nitinmukesh nope. I moved to the cloud env. They have another problem with scales but works Ok in basic. )
