### ISSUE TITLE
Deforum.py

### ISSUE THREAD

**Issue by JannisSkrycix** [deforum-art/deforum-stable-diffusion#329]
Hey, I am not seeing the Deforum Tab in stable defussion. I tried reloading and reinstalling and everything possible I think. Here is the Error Code from the cmd, I would be very thankful if someone with more knowledge than me could look at the problem. Thank you :)

From the CMD:

*** Error loading script: deforum.py
    Traceback (most recent call last):
      File "C:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 41, in <module>
        init_deforum()
      File "C:\stable-diffusion\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 33, in init_deforum
        from deforum_helpers.ui_right import on_ui_tabs
      File "C:\stable-diffusion\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 20, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (C:\stable-diffusion\stable-diffusion-webui\webui.py)

---
*** Error loading script: deforum_api.py
    Traceback (most recent call last):
      File "C:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_api.py", line 29, in <module>
        from deforum_api_models import Batch, DeforumJobErrorType, DeforumJobStatusCategory, DeforumJobPhase, DeforumJobStatus
    ModuleNotFoundError: No module named 'deforum_api_models'

---

**Comment by gulu233** [comment]
I'm facing the same problem, did you solve it?
