### ISSUE TITLE
Error: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/114763196.jpg'.

### ISSUE THREAD

**Issue by vladiyudi** [deforum-art/deforum-stable-diffusion#339]
Hello, I run Stable Diffusion on Google Colab.
When I launch Deforum - I encounter following error:

`*START OF TRACEBACK*
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/run_deforum.py", line 68, in run_deforum
    args_loaded_ok, root, args, anim_args, video_args, parseq_args, loop_args, controlnet_args = process_args(args_dict, i)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/args.py", line 1174, in process_args
    default_img = Image.open(os.path.join(pathlib.Path(__file__).parent.absolute(), '114763196.jpg'))
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/114763196.jpg'
*END OF TRACEBACK*
User friendly error message:
Error: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/114763196.jpg'. Please, check your prompts with a JSON validator.
 `
I checked target folder and didn't find this file. 
Please let me know if you have any suggestions how to fix it

**Comment by GRACOPORDEUS** [comment]
I had a similar problem

**Comment by Zoranvedek** [comment]
I'm getting similar but different:

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-bd06d2351dce>](https://localhost:8080/#) in <cell line: 6>()
     25 
     26     print(subprocess.run(['git', 'clone', 'https://github.com/deforum/k-diffusion/'], stdout=subprocess.PIPE).stdout.decode('utf-8'))
---> 27     with open('k-diffusion/k_diffusion/__init__.py', 'w') as f:
     28         f.write('')
     29 

FileNotFoundError: [Errno 2] No such file or directory: 'k-diffusion/k_diffusion/__init__.py'



...upon checking the page "https://github.com/deforum/k-diffusion/" I can confirm that it no longer exists. 

I'm at a dead end on a several months long project,  and needing to know how to move forward. Google Colab Deforum Stable Diffusion v0.5.
