### ISSUE TITLE
Settings not saved  error received  

### ISSUE THREAD

**Issue by jlitz** [deforum-art/deforum-stable-diffusion#358]
I can not save a settings file  get this error  and get the same error when generating  the save settings button strange no response
Traceback (most recent call last):
  File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\components\radio.py", line 170, in preprocess
    return [value for _, value in self.choices].index(x)
ValueError: 1 is not in list

**Comment by jlitz** [comment]
> I can not save a settings file get this error and get the same error when generating the save settings button strange no response Traceback (most recent call last): File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict output = await app.get_blocks().process_api( File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1429, in process_api inputs = self.preprocess_data(fn_index, inputs, state) File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data processed_input.append(block.preprocess(inputs[i])) File "D:\1116a\stable-diffusion-webui\venv\lib\site-packages\gradio\components\radio.py", line 170, in preprocess return [value for _, value in self.choices].index(x) ValueError: 1 is not in list

delete post solved
