### ISSUE TITLE
Problems with deforum at stable-diffusion-webui-forge-latest

### ISSUE THREAD

**Issue by KarloffS** [deforum-art/deforum-stable-diffusion#368]
This error seems to be related to version 2.1.1 of the automatic1111-webui extension for Deforum, which is causing an issue when retrieving a directory where images are obtained through the use of Hackinghub differences. This new version packs the output panel in a list, making it non-iterable, which is causing an issue while using the create_output_panel() function. The OutputPanel object needs to be defunced before it can be unpacked, which can be done by using the packaging function that adds the defunce decorator to the script. The expected output is to use the OutputPanel object to display the gallery and other information for

Error executing callback ui_tabs_callback for C:\stable-diffusion-webui-forge-latest\extensions\deforum-for-automatic1111-webui\scripts\deforum.py Traceback (most recent call last): File "C:\stable-diffusion-webui-forge-latest\modules\script_callbacks.py", line 169, in ui_tabs_callback res += c.callback() or [] File "C:\stable-diffusion-webui-forge-latest\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 92, in on_ui_tabs deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples) TypeError: cannot unpack non-iterable OutputPanel object

**Comment by Vendaciousness** [comment]
If you're using **Stable Forge,** you need switch to the spanking new version made special for Forge, located here: https://github.com/deforum-art/sd-forge-deforum

And good news is I think Rewbs (the dev) may have just fixed this bug, but if the error is still present, I hope you'll fill out a report for the issue there.
