### ISSUE TITLE
Deforum not showing in Stable Diffusion WebUI

### ISSUE THREAD

**Issue by stilld6rk** [deforum-art/deforum-stable-diffusion#369]
I installed extension by tab "Instal from url" a restart web ui a lot o times even reinstall stable diffusion and i still have this problem. On the list of extension i have Deforum but I still dont have deforum tab.
![obraz](https://github.com/deforum-art/deforum-stable-diffusion/assets/161238171/c15ad00a-9af4-429a-bb2f-501fae45ffab)

**Comment by alirezaesfandiar** [comment]
I have the same problem and this is the text

*** Error executing callback ui_tabs_callback for E:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "E:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 92, in on_ui_tabs
        deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

**Comment by BClev** [comment]
Same here. Using A111 1.8.0.

**Comment by fkiacomposer** [comment]
same problem & same error !!! 
please help

**Comment by alirezaesfandiar** [comment]
It was fixed, the new update of deforum solved the problem...✅
